<a href="https://colab.research.google.com/github/rukendar/Rukendar.s/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import pandas as pd
import numpy as np

# Creating a sample DataFrame
data = pd.DataFrame({
    'Brand': ['Maruti', 'Hyundai', 'Tata', 'Mahindra', 'Maruti', 'Hyundai', 'Renault', 'Tata', 'Maruti'],
    'Year': [2012, 2014, 2011, 2015, 2012, 2016, 2014, 2018, 2019],
    'Kms Driven': [50000, 30000, 60000, 25000, 10000, 46000, 31000, 15000, 12000],
    'City': ['Gurgaon', np.nan, 'Mumbai', 'Delhi', 'Mumbai', 'Delhi', 'Mumbai', 'Chennai', 'Ghaziabad'],
    'Mileage': [28, 27, 25, 26, 28, 29, 24, 21, 24]
})

# Displaying the DataFrame
display(data)

# Check for null values
# data.isnull()

Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012       50000    Gurgaon       28
1   Hyundai  2014       30000        NaN       27
2      Tata  2011       60000     Mumbai       25
3  Mahindra  2015       25000      Delhi       26
4    Maruti  2012       10000     Mumbai       28
5   Hyundai  2016       46000      Delhi       29
6   Renault  2014       31000     Mumbai       24
7      Tata  2018       15000    Chennai       21
8    Maruti  2019       12000  Ghaziabad       24

In [33]:
import pandas as pd
# Sample data for sales transactions and customer information
sales_data = {
    'TransactionID': [1, 2, 3, 4, 5],
    'CustomerID': [101, 102, 103, 104, 101],
    'Amount': [250, 300, 400, 500, 600],
    'Date': ['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04', '2025-01-05']
}

customer_data = {
    'CustomerID': [101, 102, 103, 104],
    'CustomerName': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [30, 35, 40, 25],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}

# Convert data into DataFrame
sales_df = pd.DataFrame(sales_data)
customers_df = pd.DataFrame(customer_data)

# Show basic structure of sales_df
print("Sales DataFrame:")
print(sales_df.head())

# 1. Exploring the dataset (using shape and describe)
print("\nShape of sales data:", sales_df.shape)  # Get number of rows and columns
print("\nSales data statistics:")
#print(sales_df.describe())  # Summary statistics
print("Sales dataframe", sales_df)
print("customers_df", customers_df)
#display(data.loc[(data.Brand == "Maruti") & (data.Year == 2012)]) #this line is causing an error, data is not defined
# Assuming you want to filter sales_df instead of an undefined 'data' dataframe
# Also, replacing the non-breaking space with a regular space
#display(sales_df.loc[(sales_df.CustomerID == 101)]) # Example filter, replace with actual condition

Sales DataFrame:
   TransactionID  CustomerID  Amount        Date
0              1         101     250  2025-01-01
1              2         102     300  2025-01-02
2              3         103     400  2025-01-03
3              4         104     500  2025-01-04
4              5         101     600  2025-01-05

Shape of sales data: (5, 4)

Sales data statistics:
Sales DataFrame:
   TransactionID  CustomerID  Amount        Date
0              1         101     250  2025-01-01
1              2         102     300  2025-01-02
2              3         103     400  2025-01-03
3              4         104     500  2025-01-04
4              5         101     600  2025-01-05

Shape of sales data: (5, 4)

Sales data statistics:
Sales dataframe    TransactionID  CustomerID  Amount        Date
0              1         101     250  2025-01-01
1              2         102     300  2025-01-02
2              3         103     400  2025-01-03
3              4         104     500  2025-01-04
4          

In [34]:
#filter brand hyundai kms driven is >30000
filtered_data = data[(data['Brand'] == 'Hyundai') & (data['Kms Driven'] > 30000)]
display(filtered_data)

Brand  Year  Kms Driven   City  Mileage
5  Hyundai  2016       46000  Delhi       29

In [35]:
#filter the data frame in such a way that city name is delhi and kms driven is >30000
filtered_data = data[(data['City'] == 'Delhi') & (data['Kms Driven'] > 30000)]
display(filtered_data)

Brand  Year  Kms Driven   City  Mileage
5  Hyundai  2016       46000  Delhi       29

In [ ]:
#apply inner , outer join and left and right join operations by

In [36]:
inner_joined_df = pd.merge(sales_df, customers_df, on='CustomerID', how='inner')
print("Inner Joined DataFrame:")
print(inner_joined_df)

Inner Joined DataFrame:
   TransactionID  CustomerID  Amount        Date CustomerName  Age  \
0              1         101     250  2025-01-01        Alice   30   
1              2         102     300  2025-01-02          Bob   35   
2              3         103     400  2025-01-03      Charlie   40   
3              4         104     500  2025-01-04        David   25   
4              5         101     600  2025-01-05        Alice   30   

          City  
0     New York  
1  Los Angeles  
2      Chicago  
3      Houston  
4     New York  


In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [30]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[-3:-1])

[7 8]


In [28]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[1,3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
9


In [27]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2 3 4 5]]


In [9]:
import numpy as np
arr = np.arange(40).reshape(4,10)
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]


In [18]:
import numpy as np
arr = np.ones((1, 2, 2))
print(arr)

[[[1. 1.]
  [1. 1.]]]


In [22]:
import numpy as np
arr = np.zeros((2, 3, 4))
print(arr)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [23]:
import numpy as np
arr = [1,2,3,4,5,6,7,8,9,10,11,12,13]
print(arr[5]+arr[8])

15
